### ISSUE TITLE
Crash when scroll messageView

### ISSUE THREAD

**Issue by veerChauhan** [mesibo/messenger-app-ios-swift#2]
when i tried to scroll message getting crash :

Thread 1: Exception: "-[MessageViewController loadMoreMessages]: unrecognized selector sent to instance 0x103022a00".

**Comment by mesibo** [comment]
Duplicate issue!

**Comment by veerChauhan** [comment]
Please merge the issue where the solution is provided

**Comment by mesibo** [comment]
New frameworks are already updated today. Please resync code.
