### ISSUE TITLE
 Showing Recent Messages Undefined symbol: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by Mayuramipara94** [mesibo/messenger-app-ios-swift#8]
![Screenshot 2020-08-11 at 2 33 43 PM](https://user-images.githubusercontent.com/26631598/89878800-aa535780-dbdf-11ea-861a-dbf28bd1391e.png)

am complete all steps successfully but still am getting "___darwin_check_fd_set_overflow"

**Comment by mesibo** [comment]
Ensure that you are using the latest Xcode. 

Also, the last step is obsolete and we have updated documentation to remove it.

Please delete the existing download, and redownload. Send entire logs if you still face issues.
